### ISSUE TITLE
cljsjs/react exclusion

### ISSUE THREAD

**Issue by madstap** [gadfly361/baking-soda#2]
Instead of doing this:

```
[reagent "0.6.0" :exclusions [cljsjs/react]]
[cljsjs/react-with-addons "15.4.2-2"]
[cljsjs/react-dom "15.4.2-2"]
[baking-soda "0.1.1"]
```

I had to do this:
```
[reagent "0.6.0" :exclusions [cljsjs/react]]
[cljsjs/react-with-addons "15.4.2-2"]
[cljsjs/react-dom "15.4.2-2" :exclusions [cljsjs/react]] ; Exclude react here as well.
[baking-soda "0.1.1"]
```
Is this just me? If so, why? If not, maybe tweak the readme?

**Comment by gadfly361** [comment]
@madstap after running `lein deps :tree` looks like react-dom does bring in a version of react, so excluding it shouldn't hurt. I'll update the README, thanks!
